### ISSUE TITLE
Migrate from Webpack to Vite

### ISSUE THREAD

**Issue by milojezek** [jg-chickenbook/chickenbook#18]
The app is built with Webpack right now. There is however a better option - Vite. Let's decide if it's worth recreating the project with Vite. As far as I know, it shouldn't be difficult. It's possible to replace Webpack with Vite in the current project.

**Comment by NikoLenCZ** [comment]
Im in, it would be better and more faster with Vite 👍

**Comment by VeveCambor** [comment]
I agree, too. :)
