### ISSUE TITLE
Migrate to TypeScript and Vite

### ISSUE THREAD

**Issue by milojezek** [jg-chickenbook/chickenbook#20]
@VeveCambor and I agreed that it would be great to migrate from JavaScript to TypeScript. Considering the current amount of code, it wouldn't be such a big deal yet.

The app is built with Webpack right now. There is however a better option - Vite. Let's decide if it's worth recreating the project with Vite. As far as I know, it shouldn't be difficult. It's possible to replace Webpack with Vite in the current project.

Definition of done:
- [x] The main language is TypeScript instead of JavaScript
- [x] Bundler is Vite instead of Webpack
- [x] Update ESLint rules to check TS syntax
- [x] The app works as before

**Comment by NikoLenCZ** [comment]
Yes! we can set the TS with migrate to Vite, if you will agree 👍

**Comment by VeveCambor** [comment]
Yes, that was my idea. We need to learn it. 😃

**Comment by milojezek** [comment]
> Yes! we can set the TS with migrate to Vite, if you will agree 👍

Yep, we can merge these issues. It's a great idea 😉

**Comment by milojezek** [comment]
I've just merged the two "migration issues". 

Is anyone particularly interested in processing the migration and preparing the project? @VeveCambor || @NikoLenCZ 🙂

I should be able to process it by our next call on Sunday but maybe one of you wants to do it. Moreover, @VeveCambor is currently working on login as far as I remember. Do we want to migrate before or after she pushes the latest changes?

**Comment by milojezek** [comment]
This issue has been completed by merging the changes to dev
