### ISSUE TITLE
Refactor Components

### ISSUE THREAD

**Issue by NikoLenCZ** [jg-chickenbook/chickenbook#22]
Refactor form inputs, select and buttons to simple components

- [ ] Buttons with theme
- [ ] Inputs
- [ ] select

**Comment by milojezek** [comment]
We discussed refactoring yesterday a bit. I'd go first with the migration stuff if we decide to do it. I'll also need the refactoring more structured and enough segmented. We can discuss it at the weekend/at the beginning of next week.

**Comment by NikoLenCZ** [comment]
@milojezek I agree, I just prepare the issue with tasks... will we have some meeting for another details?

**Comment by milojezek** [comment]
> @milojezek I agree, I just prepare the issue with tasks... will we have some meeting for another details?

We can have an extra short call and discuss the changes for this project if you want. 

The [new guide](#19) is already in PR + I'll look at issues/tasks, their definition and the division of a task into smaller tasks if necessary. Any new issue/PR should meet some criteria before a developer starts working on it. It sounds process-heavy but it won't be that hard 😀 I can update the collaboration guide with some info regarding preparing an issue.

**Comment by milojezek** [comment]
I created new issues. One of them contains the changes noted here ;)
